/**
 * ExportReportSection Component
 * AI Analysis report section visible only during PDF export
 */

import React from 'react';
import { Sparkles, FileText, AlertTriangle, HelpCircle } from 'lucide-react';
import { useTranslation } from 'react-i18next';

interface Risk {
  id?: string;
  title: string;
  description: string;
  level: 'HIGH' | 'MEDIUM' | 'LOW';
}

interface Analysis {
  score: number;
  summary: string;
  risks?: Risk[];
  questions?: string[];
}

interface ExportReportSectionProps {
  analysis: Analysis;
  isExporting: boolean;
}

export const ExportReportSection: React.FC<ExportReportSectionProps> = ({
  analysis,
  isExporting,
}) => {
  const { t } = useTranslation();

  if (!isExporting || !analysis) {
    return null;
  }

  return (
    <div className="mt-8 pt-8 border-t-2 border-slate-200">
      <h3 className="font-bold text-xl text-slate-900 mb-6 flex items-center gap-2">
        <Sparkles className="text-blue-600" size={24} />
        {t('report.aiSafetyReport')}
      </h3>

      {/* Score */}
      <div className="bg-slate-50 rounded-xl p-6 mb-6 flex items-center justify-between border border-slate-200">
        <div>
          <p className="text-sm text-slate-500 font-bold uppercase">{t('report.safetyScore')}</p>
          <div className="flex items-end gap-2">
            <span className="text-4xl font-bold text-blue-600">{analysis.score}</span>
            <span className="text-lg text-slate-400 mb-1">/ 100</span>
          </div>
        </div>
        <div className="text-right">
          <p className="text-sm font-semibold text-slate-700">
            {t('report.createdAt')}: {new Date().toLocaleDateString()}
          </p>
          <p className="text-xs text-slate-400">SafeContract AI Analysis</p>
        </div>
      </div>

      {/* Summary */}
      <div className="mb-8">
        <h4 className="font-bold text-slate-800 mb-3 flex items-center gap-2 text-lg">
          <FileText size={20} className="text-slate-500" /> {t('report.summary')}
        </h4>
        <div className="bg-white p-4 rounded-xl border border-slate-200 text-slate-700 text-sm leading-relaxed shadow-sm">
          {analysis.summary}
        </div>
      </div>

      {/* Risks */}
      <div className="mb-8">
        <h4 className="font-bold text-slate-800 mb-3 flex items-center gap-2 text-lg">
          <AlertTriangle size={20} className="text-orange-500" />
          {t('report.detectedRisks')} ({analysis.risks?.length || 0})
        </h4>
        <div className="space-y-4">
          {(analysis.risks || []).map((risk, idx) => (
            <div
              key={risk.id || idx}
              className="bg-white p-4 rounded-xl border-l-4 border-l-orange-500 border-y border-r border-slate-200 shadow-sm"
            >
              <div className="flex justify-between items-start mb-2">
                <span className="font-bold text-slate-900">{risk.title}</span>
                <span
                  className={`text-xs px-2 py-0.5 rounded font-bold ${
                    risk.level === 'HIGH'
                      ? 'bg-red-100 text-red-700'
                      : risk.level === 'MEDIUM'
                      ? 'bg-orange-100 text-orange-700'
                      : 'bg-yellow-100 text-yellow-700'
                  }`}
                >
                  {risk.level}
                </span>
              </div>
              <p className="text-sm text-slate-600">{risk.description}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Questions */}
      <div className="mb-8">
        <h4 className="font-bold text-slate-800 mb-3 flex items-center gap-2 text-lg">
          <HelpCircle size={20} className="text-blue-500" />
          {t('report.suggestedQuestions')}
        </h4>
        <div className="bg-blue-50 rounded-xl p-5 border border-blue-100">
          <ul className="space-y-3">
            {(analysis.questions || []).map((q, i) => (
              <li key={i} className="flex gap-3 text-sm text-slate-700 items-start">
                <div className="w-5 h-5 bg-white rounded-full flex items-center justify-center text-blue-500 text-xs font-bold shadow-sm flex-shrink-0 mt-0.5">
                  {i + 1}
                </div>
                {q}
              </li>
            ))}
          </ul>
        </div>
      </div>

      <div className="text-center mt-12 pt-6 border-t border-slate-200">
        <p className="text-xs text-slate-400">{t('report.disclaimer')}</p>
        <p className="text-[10px] text-slate-300 mt-1">Generated by SafeContract</p>
      </div>
    </div>
  );
};
